### ISSUE TITLE
ES error :(

### ISSUE THREAD

**Issue by nerdprogrammergm** [machinebox/textbox_elastic_indexer#1]
When trying to run the indexer using the command, "go run indexer.go", I am getting the error 
"2017/10/14 00:42:59 [ERROR]: Inserting article bbcsport/athletics/085.txt ES error:Post http://localhost:9200/news_textbox/articles: dial tcp [::1]:9200: getsockopt: connection refused
"

Is this elastic search error?
Some problem with installation or configuration if elastic search and kibana?
Please help!

**Comment by dahernan** [comment]
it looks like ES is not up, make sure ES is running,  `$ curl http://localhost:9200`
